tap "felixkratz/formulae" # jankyborders
tap "homebrew/bundle"
tap "nikitabobko/tap" # aerospace
brew "bat"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "mas"
brew "mise"
brew "rcm"
brew "starship"
brew "terminal-notifier"
brew "felixkratz/formulae/borders"
cask "aerospace"
cask "livebook"
cask "sensiblesidebuttons"
cask "spotify"
cask "unnaturalscrollwheels"
mas "Perculia", id: 1462633284
vscode "alefragnani.project-manager"
vscode "antiantisepticeye.vscode-color-picker"
vscode "bierner.emojisense"
vscode "christian-kohler.npm-intellisense"
vscode "cliffordfajardo.highlight-line-vscode"
vscode "dbaeumer.vscode-eslint"
vscode "dericcain.feather"
vscode "dotjoshjohnson.xml"
vscode "edonet.vscode-command-runner"
vscode "esbenp.prettier-vscode"
vscode "fabiospampinato.vscode-diff"
vscode "firsttris.vscode-jest-runner"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "grapecity.gc-excelviewer"
vscode "graphql.vscode-graphql"
vscode "graphql.vscode-graphql-syntax"
vscode "jakebecker.elixir-ls"
vscode "l13rary.l13-diff"
vscode "marp-team.marp-vscode"
vscode "mechatroner.rainbow-csv"
vscode "mgmcdermott.vscode-language-babel"
vscode "mhutchie.git-graph"
vscode "mikeburgh.xml-format"
vscode "mikestead.dotenv"
vscode "mousetraps.selected-character-count"
vscode "mrmlnc.vscode-apache"
vscode "mrmlnc.vscode-scss"
vscode "mushan.vscode-paste-image"
vscode "nhoizey.gremlins"
vscode "nicoespeon.abracadabra"
vscode "peterschmalfeldt.explorer-exclude"
vscode "redhat.java"
vscode "runningcoder.react-snippets"
vscode "tyriar.lorem-ipsum"
vscode "unifiedjs.vscode-mdx"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vitaliymaz.vscode-svg-previewer"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "waderyan.gitblame"
vscode "wayou.vscode-todo-highlight"
vscode "wix.glean"
vscode "wmaurer.change-case"
vscode "yoavbls.pretty-ts-errors"
vscode "ziyasal.vscode-open-in-github"

# Potentials, from previous camnda machine:
# brew "erlang"
# brew "elixir"
# brew "exercism"
# brew "gnu-sed"
# brew "grep"
# brew "jq"
# brew "lychee"
# brew "mkcert"
# brew "openssl@1.1"
# brew "postgresql@14"
# brew "python@3.9"
# brew "vale"
# brew "xq"
# brew "koekeishiya/formulae/yabai"
# cask "blackhole-16ch"
# cask "fork"
# cask "insomnia"
# cask "livebook"
# vscode "redvanworkshop.explorer-exclude-vscode-extension"