code --install-extension alefragnani.project-manager
code --install-extension antiantisepticeye.vscode-color-picker
code --install-extension bierner.emojisense
code --install-extension christian-kohler.npm-intellisense
code --install-extension cliffordfajardo.highlight-line-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension dericcain.feather
code --install-extension dotjoshjohnson.xml
code --install-extension edonet.vscode-command-runner
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-diff
code --install-extension firsttris.vscode-jest-runner
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-github-actions
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension grapecity.gc-excelviewer
code --install-extension graphql.vscode-graphql
code --install-extension graphql.vscode-graphql-syntax
code --install-extension jakebecker.elixir-ls
code --install-extension l13rary.l13-diff
code --install-extension marp-team.marp-vscode
code --install-extension mechatroner.rainbow-csv
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension mikeburgh.xml-format
code --install-extension mikestead.dotenv
code --install-extension mousetraps.selected-character-count
code --install-extension mrmlnc.vscode-apache
code --install-extension mrmlnc.vscode-scss
code --install-extension mushan.vscode-paste-image
code --install-extension nhoizey.gremlins
code --install-extension nicoespeon.abracadabra
code --install-extension peterschmalfeldt.explorer-exclude
code --install-extension redhat.java
code --install-extension runningcoder.react-snippets
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension travisthetechie.write-good-linter
code --install-extension tyriar.lorem-ipsum
code --install-extension unifiedjs.vscode-mdx
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vitaliymaz.vscode-svg-previewer
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension wix.glean
code --install-extension wmaurer.change-case
code --install-extension yoavbls.pretty-ts-errors
code --install-extension ziyasal.vscode-open-in-github