code --install-extension alefragnani.project-manager
code --install-extension 1antiantisepticeye.vscode-color-picker
code --install-extension 1bierner.emojisense
code --install-extension 1christian-kohler.npm-intellisense
code --install-extension 1cliffordfajardo.highlight-line-vscode
code --install-extension 1dbaeumer.vscode-eslint
code --install-extension 1dericcain.feather
code --install-extension 1dotjoshjohnson.xml
code --install-extension 1edonet.vscode-command-runner
code --install-extension 1esbenp.prettier-vscode
code --install-extension 1fabiospampinato.vscode-diff
code --install-extension 1firsttris.vscode-jest-runner
code --install-extension 1github.copilot
code --install-extension 1github.copilot-chat
code --install-extension 1github.vscode-github-actions
code --install-extension 1github.vscode-pull-request-github
code --install-extension 1golang.go
code --install-extension 1grapecity.gc-excelviewer
code --install-extension 1graphql.vscode-graphql
code --install-extension 1graphql.vscode-graphql-syntax
code --install-extension 1jakebecker.elixir-ls
code --install-extension 1l13rary.l13-diff
code --install-extension 1marp-team.marp-vscode
code --install-extension 1mechatroner.rainbow-csv
code --install-extension 1mgmcdermott.vscode-language-babel
code --install-extension 1mhutchie.git-graph
code --install-extension 1mikeburgh.xml-format
code --install-extension 1mikestead.dotenv
code --install-extension 1mousetraps.selected-character-count
code --install-extension 1mrmlnc.vscode-apache
code --install-extension 1mrmlnc.vscode-scss
code --install-extension 1mushan.vscode-paste-image
code --install-extension 1nhoizey.gremlins
code --install-extension 1nicoespeon.abracadabra
code --install-extension 1peterschmalfeldt.explorer-exclude
code --install-extension 1redhat.java
code --install-extension 1runningcoder.react-snippets
code --install-extension 1streetsidesoftware.code-spell-checker
code --install-extension 1travisthetechie.write-good-linter
code --install-extension 1tyriar.lorem-ipsum
code --install-extension 1unifiedjs.vscode-mdx
code --install-extension 1visualstudioexptteam.intellicode-api-usage-examples
code --install-extension 1visualstudioexptteam.vscodeintellicode
code --install-extension 1vitaliymaz.vscode-svg-previewer
code --install-extension 1vscjava.vscode-gradle
code --install-extension 1vscjava.vscode-java-debug
code --install-extension 1vscjava.vscode-java-dependency
code --install-extension 1vscjava.vscode-java-pack
code --install-extension 1vscjava.vscode-java-test
code --install-extension 1vscjava.vscode-maven
code --install-extension 1waderyan.gitblame
code --install-extension 1wayou.vscode-todo-highlight
code --install-extension 1wix.glean
code --install-extension 1wmaurer.change-case
code --install-extension 1yoavbls.pretty-ts-errors
code --install-extension 1ziyasal.vscode-open-in-github
